using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace ExportBill
{
    public partial class DXMain : DevExpress.XtraEditors.XtraForm
    {
        public DXMain()
        {
            InitializeComponent();
            this.Load += Form1_Load;
            //end-users cannot add rows
            gridView1.OptionsBehavior.AllowAddRows = DevExpress.Utils.DefaultBoolean.False;
            //gridControl1.DataSource = SampleDS();
            // This line of code is generated by Data Source Configuration Wizard
        }
        private void Form1_Load(object sender, EventArgs e)
        {
            this.gridControl1.DataSource = SampleDS();
            gridView1.AddNewRow();
            gridView1.SetRowCellValue(1, gridView1.Columns[1], "Please enter new value");
            //if (gridView1.IsNewItemRow(rowHandle))
            //{
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[1], "Lam");
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[2], "123456789");
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[3], "Air-Black");
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[4], "Hung");
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[5], "Thay nhot");
            //    gridView1.SetRowCellValue(rowHandle, gridView1.Columns[6], 123000);
            //}
            //load sample data base//add a new row
            //this.gridControl2.DataSource = SampleDS();
            //set a new row cell value. The static GridControl.NewItemRowHandle field allows you to retrieve the added row
            //gridView2.SetRowCellValue(0, gridView2.Columns["UserName"], "Please enter new value");
        }
        public BindingList<Entry> SampleDS()
        {
            BindingList<Entry> ds = new BindingList<Entry>();
            ds.Add(new Entry("123", "Lam", "123456789", "Air-Black", "Hung", "Thay nhot", "print", 123000));
            ds.Add(new Entry("124","Tri", "33719", "Exciter", "Hoang", "Thay phut", "print", 500000));
            ds.AllowNew = true;
            return ds;
        }
        private void gridControl1_Click(object sender, EventArgs e)
        {
            //OpenFileDialog ox = new OpenFileDialog();
            //if (ox.ShowDialog() == DialogResult.OK)
            //{
            //    var filename = ox.FileName;
            //    this.gridControl2.ExportToXlsx(filename);
            //}
        }
    }
    public class Entry
    {
        public Entry() { }
        public Entry(string view, string userName, string bs, string lx, string tsc, string dg, string print, decimal tt)
        {
            View = view;
            UserName = userName;
            BS = bs;
            LX = lx;
            TSC = tsc;
            DG = dg;
            PrintBill = print;
            TT = tt;
        }
        public string View { get; set; }
        public string UserName { get; set; }
        public string BS { get; set; }
        public string LX { get; set; }
        public string TSC { get; set; }
        public string DG { get; set; }
        public decimal TT { get; set; }
        public string PrintBill { get; set; }
    }
}